controllers:
    resource: ../src/Controller/
    type: attribute

app_event_add:
    path: /event/add
    controller: App\Controller\EventController::add

app_event_list:
    path: /event/list
    controller: App\Controller\EventController::list

app_event_edit:
    path: /event/edit/{id}
    controller: App\Controller\EventController::edit

app_event_delete:
    path: /event/delete/{id}
    methods: [POST]
    controller: App\Controller\EventController::delete

app_event_search:
    path: /event/search
    controller: App\Controller\EventController::search

app_logout:
  path: /logout
  methods: [POST]
